[project]
name = "aoc"
version = "0.1.0"
dependencies = [
    "requests",
    "pytest"
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
    "years"
]
python_files = [
    "test_*.py",
    "part1.py",
    "part2.py"
]
